// ============ CATEGORIES ============
export const categories = [
  { id: 'vitamins', name: 'Vitamins & Supplements', image: 'https://customer-assets.emergentagent.com/job_zip-validator-4/artifacts/d17t0cqc_image.png', productCount: 245 },
  { id: 'cold-flu', name: 'Cold & Flu', image: 'https://images.unsplash.com/photo-1729949129758-0b668478dce5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMjV8MHwxfHNlYXJjaHwxfHxwaGFybWFjeSUyMG1lZGljaW5lfGVufDB8fHx8MTc3MzMyODk4MXww&ixlib=rb-4.1.0&q=85', productCount: 128 },
  { id: 'pain-relief', name: 'Pain Relief', image: 'https://images.unsplash.com/photo-1550572017-26b5655c1e8c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMjV8MHwxfHNlYXJjaHw0fHxwaGFybWFjeSUyMG1lZGljaW5lfGVufDB8fHx8MTc3MzMyODk4MXww&ixlib=rb-4.1.0&q=85', productCount: 156 },
  { id: 'diabetes-care', name: 'Diabetes Care', image: 'https://images.unsplash.com/photo-1729949127847-7573ecb58bd8?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMjV8MHwxfHNlYXJjaHwyfHxwaGFybWFjeSUyMG1lZGljaW5lfGVufDB8fHx8MTc3MzMyODk4MXww&ixlib=rb-4.1.0&q=85', productCount: 89 },
  { id: 'skincare', name: 'Skincare', image: 'https://images.unsplash.com/photo-1613803745799-ba6c10aace85?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzV8MHwxfHNlYXJjaHwyfHxza2luY2FyZSUyMHByb2R1Y3RzfGVufDB8fHx8MTc3MzMyODk4NXww&ixlib=rb-4.1.0&q=85', productCount: 312 },
  { id: 'baby-care', name: 'Baby Care', image: 'https://images.unsplash.com/photo-1734599397715-f030c6d206a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWJ5JTIwY2FyZSUyMHByb2R1Y3RzfGVufDF8fHx8MTc3MzIzNzk3MHww&ixlib=rb-4.1.0&q=80&w=1080', productCount: 198 },
  { id: 'personal-care', name: 'Personal Care', image: 'https://images.unsplash.com/photo-1580870069867-74c57ee1bb07?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzV8MHwxfHNlYXJjaHwxfHxza2luY2FyZSUyMHByb2R1Y3RzfGVufDB8fHx8MTc3MzMyODk4NXww&ixlib=rb-4.1.0&q=85', productCount: 267 },
  { id: 'wellness', name: 'Wellness & Fitness', image: 'https://images.unsplash.com/photo-1759476532819-e37ac3d05cff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWxsbmVzcyUyMGZpdG5lc3MlMjBoZWFsdGh8ZW58MXx8fHwxNzczMjc5NzY3fDA&ixlib=rb-4.1.0&q=80&w=1080', productCount: 176 },
];

// Shared images per category
const IMG = {
  vit: 'https://customer-assets.emergentagent.com/job_zip-validator-4/artifacts/d17t0cqc_image.png',
  vit2: 'https://images.unsplash.com/photo-1729544015876-ea9b1cf1f1a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2aXRhbWlucyUyMHN1cHBsZW1lbnRzJTIwaGVhbHRoY2FyZXxlbnwxfHx8fDE3NzMzMTkwMDF8MA&ixlib=rb-4.1.0&q=80&w=1080',
  cold: 'https://images.unsplash.com/photo-1729949129758-0b668478dce5?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMjV8MHwxfHNlYXJjaHwxfHxwaGFybWFjeSUyMG1lZGljaW5lfGVufDB8fHx8MTc3MzMyODk4MXww&ixlib=rb-4.1.0&q=85',
  cold2: 'https://images.unsplash.com/photo-1707933504549-ab5fd91cf365?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWluJTIwcmVsaWVmJTIwbWVkaWNhdGlvbnxlbnwxfHx8fDE3NzMzMDQwMjZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
  pain: 'https://images.unsplash.com/photo-1550572017-26b5655c1e8c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMjV8MHwxfHNlYXJjaHw0fHxwaGFybWFjeSUyMG1lZGljaW5lfGVufDB8fHx8MTc3MzMyODk4MXww&ixlib=rb-4.1.0&q=85',
  pain2: 'https://images.unsplash.com/photo-1763142843470-9a9e9db7f68f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaGFybWFjeSUyMG1lZGljaW5lJTIwYm90dGxlc3xlbnwxfHx8fDE3NzMyOTQ5MDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
  diab: 'https://images.unsplash.com/photo-1729949127847-7573ecb58bd8?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMjV8MHwxfHNlYXJjaHwyfHxwaGFybWFjeSUyMG1lZGljaW5lfGVufDB8fHx8MTc3MzMyODk4MXww&ixlib=rb-4.1.0&q=85',
  diab2: 'https://images.unsplash.com/photo-1758691462814-485c3672e447?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpY2FsJTIwcHJlc2NyaXB0aW9uJTIwaGVhbHRoY2FyZXxlbnwxfHx8fDE3NzMzMjA1NTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
  skin: 'https://images.unsplash.com/photo-1613803745799-ba6c10aace85?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzV8MHwxfHNlYXJjaHwyfHxza2luY2FyZSUyMHByb2R1Y3RzfGVufDB8fHx8MTc3MzMyODk4NXww&ixlib=rb-4.1.0&q=85',
  skin2: 'https://images.unsplash.com/photo-1631390179406-0bfe17e9f89d?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzV8MHwxfHNlYXJjaHw0fHxza2luY2FyZSUyMHByb2R1Y3RzfGVufDB8fHx8MTc3MzMyODk4NXww&ixlib=rb-4.1.0&q=85',
  skin3: 'https://images.unsplash.com/photo-1765852549902-bd9c79d01afb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxza2luY2FyZSUyMGNvc21ldGljcyUyMGJvdHRsZXN8ZW58MXx8fHwxNzczMjM3MDcwfDA&ixlib=rb-4.1.0&q=80&w=1080',
  baby: 'https://images.unsplash.com/photo-1734599397715-f030c6d206a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWJ5JTIwY2FyZSUyMHByb2R1Y3RzfGVufDF8fHx8MTc3MzIzNzk3MHww&ixlib=rb-4.1.0&q=80&w=1080',
  pers: 'https://images.unsplash.com/photo-1580870069867-74c57ee1bb07?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzV8MHwxfHNlYXJjaHwxfHxza2luY2FyZSUyMHByb2R1Y3RzfGVufDB8fHx8MTc3MzMyODk4NXww&ixlib=rb-4.1.0&q=85',
  pers2: 'https://images.unsplash.com/photo-1576091358783-a212ec293ff3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwaGFybWFjaXN0JTIwY29uc3VsdGF0aW9uJTIwaGVhbHRoY2FyZXxlbnwxfHx8fDE3NzMzMjA1NTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
  well: 'https://images.unsplash.com/photo-1759476532819-e37ac3d05cff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWxsbmVzcyUyMGZpdG5lc3MlMjBoZWFsdGh8ZW58MXx8fHwxNzczMjc5NzY3fDA&ixlib=rb-4.1.0&q=80&w=1080',
};

// ============ 40 REAL AMAZON TOP-SELLING PRODUCTS ============
export const products = [
  // ===== VITAMINS & SUPPLEMENTS (5) =====
  { id: '1', name: 'Nature Made Vitamin D3 2000 IU', brand: 'Nature Made', category: 'vitamins', image: IMG.vit, strength: '2000 IU (50mcg)', dosageForm: 'Softgels', packSize: '250 Softgels', price: 13.71, originalPrice: 18.99, discount: 28, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 80407, description: '#1 Pharmacist Recommended Vitamin D brand. Supports bone, teeth, muscle, and immune health. USP verified for purity and potency.', ingredients: ['Vitamin D3 (Cholecalciferol) 2000 IU', 'Soybean Oil', 'Gelatin', 'Glycerin', 'Corn Oil'], usage: 'Take 1 softgel daily with water and a meal.', warnings: 'If pregnant, nursing, or taking medication, consult your doctor before use.' },
  { id: '2', name: 'Nature Made Vitamin C 500mg Gummies', brand: 'Nature Made', category: 'vitamins', image: IMG.vit, strength: '500mg', dosageForm: 'Gummies', packSize: '60 Gummies', price: 12.99, originalPrice: 16.49, discount: 21, inStock: true, prescriptionRequired: false, rating: 4.7, reviews: 34521, description: 'Extra Strength Vitamin C Gummies for immune system support. Delicious orange flavor. USP verified.', ingredients: ['Vitamin C (Ascorbic Acid) 500mg', 'Glucose Syrup', 'Sugar', 'Pectin', 'Citric Acid'], usage: 'Adults chew 1 gummy daily. Do not exceed recommended dosage.', warnings: 'Keep out of reach of children.' },
  { id: '3', name: 'NOW Foods Vitamin D3 + K2', brand: 'NOW Foods', category: 'vitamins', image: IMG.vit2, strength: '5000 IU D3 + 120mcg K2', dosageForm: 'Capsules', packSize: '120 Veg Capsules', price: 8.88, originalPrice: 12.99, discount: 32, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 23119, description: 'Vitamin D3 and K2 work synergistically for calcium metabolism, bone health, and cardiovascular support.', ingredients: ['Vitamin D3 5000 IU', 'Vitamin K2 (MK-7) 120mcg', 'Cellulose', 'Silica'], usage: 'Take 1 capsule every 2 days with a fat-containing meal.', warnings: 'Consult physician if taking blood thinners.' },
  { id: '4', name: 'Nature Made Fish Oil 1200mg Omega-3', brand: 'Nature Made', category: 'vitamins', image: IMG.vit, strength: '1200mg (720mg Omega-3)', dosageForm: 'Softgels', packSize: '200 Softgels', price: 14.99, originalPrice: 22.49, discount: 33, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 45672, description: 'Burp-Less formula. Supports heart health with EPA and DHA Omega-3 fatty acids. USP verified.', ingredients: ['Fish Oil Concentrate 1200mg', 'EPA 360mg', 'DHA 240mg', 'Gelatin', 'Glycerin'], usage: 'Take 1 softgel 1-2 times daily with water and a meal.', warnings: 'If you are allergic to fish, do not use. Consult your doctor if taking blood thinners.' },
  { id: '5', name: 'Nature Made Calcium Magnesium Zinc + D3', brand: 'Nature Made', category: 'vitamins', image: IMG.vit2, strength: '333mg Ca / 133mg Mg / 5mg Zn', dosageForm: 'Tablets', packSize: '300 Tablets', price: 12.49, originalPrice: 17.99, discount: 31, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 15205, description: 'Multi-mineral supplement with Vitamin D3 for bone strength, muscle function, and immune support.', ingredients: ['Calcium Carbonate 333mg', 'Magnesium Oxide 133mg', 'Zinc Oxide 5mg', 'Vitamin D3 400 IU'], usage: 'Take 3 tablets daily with water and a meal.', warnings: 'Do not exceed recommended dosage.' },

  // ===== COLD & FLU (5) =====
  { id: '6', name: 'Vicks NyQuil Severe Cold & Flu', brand: 'Vicks', category: 'cold-flu', image: IMG.cold, strength: 'Maximum Strength', dosageForm: 'Liquid', packSize: '12 fl oz', price: 15.97, originalPrice: 19.99, discount: 20, inStock: true, prescriptionRequired: false, rating: 4.7, reviews: 28934, description: 'Nighttime relief for sneezing, sore throat, headache, minor aches, fever, runny nose, and cough. Berry flavor.', ingredients: ['Acetaminophen 650mg', 'Dextromethorphan HBr 20mg', 'Doxylamine Succinate 12.5mg', 'Phenylephrine HCl 10mg'], usage: 'Adults: Take 30mL every 4 hours. Max 4 doses in 24 hours.', warnings: 'Do not use with other acetaminophen products. May cause drowsiness.' },

  { id: '8', name: 'Tylenol Cold + Flu Severe Day & Night', brand: 'Tylenol', category: 'cold-flu', image: IMG.cold, strength: 'Multi-Symptom', dosageForm: 'Caplets', packSize: '24 Caplets', price: 14.99, inStock: true, prescriptionRequired: false, rating: 4.5, reviews: 18762, description: 'Day & Night combo pack. Relieves tough cold and flu symptoms including fever, headache, sore throat, and congestion.', ingredients: ['Acetaminophen 325mg', 'Phenylephrine HCl 5mg', 'Dextromethorphan HBr 10mg', 'Guaifenesin 200mg'], usage: 'Adults: Take 2 caplets every 4 hours. Max 10 caplets in 24 hours.', warnings: 'Do not use with other acetaminophen-containing products.' },

  { id: '10', name: 'Boiron Oscillococcinum', brand: 'Boiron', category: 'cold-flu', image: IMG.cold, strength: 'Homeopathic', dosageForm: 'Quick-Dissolving Pellets', packSize: '12 Doses', price: 16.99, originalPrice: 21.99, discount: 23, inStock: true, prescriptionRequired: false, rating: 4.5, reviews: 34210, description: '#1 Pharmacist Recommended homeopathic flu medicine. Reduces duration and severity of flu-like symptoms.', ingredients: ['Anas Barbariae 200CK'], usage: 'At onset: dissolve 1 tube under tongue every 6 hours, up to 3 times a day.', warnings: 'Consult doctor if symptoms persist beyond 3 days or worsen.' },

  // ===== PAIN RELIEF (5) =====
  { id: '11', name: 'Advil Ibuprofen 200mg Tablets', brand: 'Advil', category: 'pain-relief', image: IMG.pain, strength: '200mg', dosageForm: 'Coated Tablets', packSize: '200 Tablets', price: 14.97, originalPrice: 18.99, discount: 21, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 67823, description: 'Fast-acting pain reliever and fever reducer. Provides up to 8 hours of relief for headaches, muscle aches, and minor arthritis pain.', ingredients: ['Ibuprofen 200mg', 'Corn Starch', 'FD&C Yellow No. 6', 'Sodium Lauryl Sulfate'], usage: 'Adults: 1-2 tablets every 4-6 hours. Do not exceed 3 tablets in 24 hours.', warnings: 'Take with food or milk if stomach upset occurs. NSAIDs may increase risk of heart attack or stroke.' },
  { id: '12', name: 'Tylenol Extra Strength 500mg', brand: 'Tylenol', category: 'pain-relief', image: IMG.pain2, strength: '500mg', dosageForm: 'Caplets', packSize: '225 Caplets', price: 15.47, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 91234, description: '#1 Doctor Recommended pain reliever brand. Works fast on tough pain. Safe for stomach lining when used as directed.', ingredients: ['Acetaminophen 500mg', 'Corn Starch', 'Powdered Cellulose', 'Sodium Starch Glycolate'], usage: 'Adults: 2 caplets every 6 hours. Max 6 caplets in 24 hours.', warnings: 'Severe liver damage may occur if you take more than directed or with 3+ alcoholic drinks daily.' },
  { id: '13', name: 'Aleve Naproxen Sodium 220mg', brand: 'Aleve', category: 'pain-relief', image: IMG.pain, strength: '220mg', dosageForm: 'Caplets', packSize: '270 Caplets', price: 16.97, originalPrice: 21.99, discount: 23, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 43567, description: 'All day strong. Up to 12 hours of pain relief with just 1 pill. Effective for back pain, muscle pain, and headaches.', ingredients: ['Naproxen Sodium 220mg', 'FD&C Blue No. 2', 'Magnesium Stearate', 'Povidone'], usage: 'Take 1 caplet every 8-12 hours. Do not exceed 2 caplets in 12 hours.', warnings: 'NSAIDs may cause severe stomach bleeding. Not for use before or after heart surgery.' },
  { id: '14', name: 'Biofreeze Pain Relief Gel', brand: 'Biofreeze', category: 'pain-relief', image: IMG.pain2, strength: '4% Menthol', dosageForm: 'Gel', packSize: '3 oz Tube', price: 11.99, originalPrice: 14.99, discount: 20, inStock: true, prescriptionRequired: false, rating: 4.6, reviews: 56789, description: '#1 Clinically Recommended topical pain relief brand. Fast-acting menthol formula for muscle and joint pain.', ingredients: ['Menthol 4%', 'Camphor', 'Isopropyl Alcohol', 'Carbomer', 'Herbal Extract'], usage: 'Apply generously to affected area. Massage until absorbed. Use up to 4 times daily.', warnings: 'For external use only. Avoid eyes and mucous membranes. Do not bandage tightly.' },
  { id: '15', name: 'Excedrin Migraine Relief', brand: 'Excedrin', category: 'pain-relief', image: IMG.pain, strength: 'Multi-Action', dosageForm: 'Caplets', packSize: '200 Caplets', price: 19.94, inStock: true, prescriptionRequired: false, rating: 4.7, reviews: 38901, description: 'First FDA-approved OTC migraine medicine. Combination formula targets migraine pain from multiple angles.', ingredients: ['Acetaminophen 250mg', 'Aspirin 250mg', 'Caffeine 65mg'], usage: 'Adults: 2 caplets with a full glass of water. May repeat after 6 hours. Max 2 doses in 24 hours.', warnings: 'Contains aspirin. Not for children under 18 with flu symptoms. Contains caffeine.' },

  // ===== DIABETES CARE (5) =====
  { id: '16', name: 'OneTouch Ultra Blue Test Strips', brand: 'OneTouch', category: 'diabetes-care', image: IMG.diab, strength: 'Blood Glucose', dosageForm: 'Test Strips', packSize: '100 Strips', price: 69.99, originalPrice: 89.99, discount: 22, inStock: true, prescriptionRequired: false, rating: 4.7, reviews: 24567, description: '#1 Brand recommended by endocrinologists. Fast and accurate blood glucose testing in just 5 seconds.', ingredients: ['Glucose Oxidase Enzyme', 'Electrode Strips', 'Quality Control Chemistry'], usage: 'Insert strip into OneTouch meter. Apply blood sample to edge of strip. Read results in 5 seconds.', warnings: 'For in vitro diagnostic use only. Do not reuse strips.' },
  { id: '17', name: 'Glucerna Diabetes Nutritional Shake', brand: 'Glucerna', category: 'diabetes-care', image: IMG.diab2, strength: '10g Protein', dosageForm: 'Ready-to-Drink Shake', packSize: '24 Pack (8 fl oz each)', price: 38.99, originalPrice: 49.99, discount: 22, inStock: true, prescriptionRequired: false, rating: 4.6, reviews: 31245, description: '#1 Doctor Recommended diabetes nutrition shake. CARBSTEADY to help minimize blood sugar spikes. Rich Chocolate flavor.', ingredients: ['Milk Protein Concentrate', 'Fructose', 'Cocoa Powder', 'Canola Oil', 'Vitamins & Minerals'], usage: 'Shake well. Use as a meal or snack replacement. Serve chilled for best taste.', warnings: 'Not for use as a sole source of nutrition. Consult your physician.' },
  { id: '18', name: 'Nature Made Diabetes Health Pack', brand: 'Nature Made', category: 'diabetes-care', image: IMG.diab, strength: 'Multi-Nutrient', dosageForm: 'Daily Supplement Packets', packSize: '60 Packets (30 day)', price: 24.99, originalPrice: 32.99, discount: 24, inStock: true, prescriptionRequired: false, rating: 4.5, reviews: 8765, description: 'Comprehensive daily supplement pack with key nutrients for people with diabetes. Includes Vitamin D, Magnesium, and more.', ingredients: ['Vitamin C 500mg', 'Vitamin D3 2000 IU', 'Vitamin B12', 'Magnesium 250mg', 'Fish Oil 1200mg', 'Alpha Lipoic Acid 200mg'], usage: 'Take 1 packet daily with food.', warnings: 'Consult your healthcare provider before use with diabetes medications.' },
  { id: '19', name: 'Freestyle Libre 3 Reader', brand: 'Abbott', category: 'diabetes-care', image: IMG.diab2, strength: 'CGM System', dosageForm: 'Reader Device', packSize: '1 Reader', price: 75.99, inStock: true, prescriptionRequired: true, rating: 4.6, reviews: 15432, description: 'Continuous Glucose Monitor. Worlds smallest, thinnest glucose sensor. Real-time glucose readings without fingersticks.', ingredients: ['Digital Reader', 'USB-C Charging Cable', 'Quick Start Guide'], usage: 'Scan sensor with reader to get glucose readings. Sensor lasts up to 14 days.', warnings: 'Prescription required. Consult your doctor for proper use and calibration.' },
  { id: '20', name: 'Berberine HCl 1200mg', brand: "Nature's Bounty", category: 'diabetes-care', image: IMG.diab, strength: '1200mg', dosageForm: 'Capsules', packSize: '60 Capsules', price: 19.99, originalPrice: 27.99, discount: 29, inStock: true, prescriptionRequired: false, rating: 4.4, reviews: 19876, description: 'Plant-based supplement supporting healthy blood sugar levels already within normal range. Non-GMO and gluten-free.', ingredients: ['Berberine HCl 1200mg', 'Gelatin Capsule', 'Rice Flour', 'Magnesium Stearate'], usage: 'Take 1 capsule twice daily with meals.', warnings: 'May interact with diabetes and blood pressure medications. Consult doctor before use.' },

  // ===== SKINCARE (5) =====
  { id: '21', name: 'CeraVe Moisturizing Cream', brand: 'CeraVe', category: 'skincare', image: IMG.skin, strength: 'With 3 Essential Ceramides', dosageForm: 'Cream', packSize: '19 oz (539g)', price: 18.59, originalPrice: 22.99, discount: 19, inStock: true, prescriptionRequired: false, rating: 4.7, reviews: 96351, description: '#1 Dermatologist Recommended moisturizer. With MVE Technology for 24-hour hydration. Fragrance-free, non-comedogenic.', ingredients: ['Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Hyaluronic Acid', 'Cholesterol', 'Dimethicone'], usage: 'Apply liberally to face and body as needed. Ideal for dry to very dry skin.', warnings: 'For external use only. Discontinue use if irritation occurs.' },
  { id: '22', name: 'CeraVe Foaming Facial Cleanser', brand: 'CeraVe', category: 'skincare', image: IMG.skin2, strength: 'Gel-to-Foam', dosageForm: 'Cleanser', packSize: '16 fl oz', price: 15.99, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 95284, description: 'Removes excess oil without disrupting the skin barrier. With ceramides, niacinamide, and hyaluronic acid. Non-comedogenic.', ingredients: ['Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Niacinamide', 'Hyaluronic Acid', 'Sodium Lauroyl Lactylate'], usage: 'Wet skin, massage cleanser into skin in circular motion, rinse. Use AM and PM.', warnings: 'Avoid contact with eyes. For external use only.' },
  { id: '23', name: 'Neutrogena Hydro Boost Water Gel', brand: 'Neutrogena', category: 'skincare', image: IMG.skin3, strength: 'Hyaluronic Acid', dosageForm: 'Gel Moisturizer', packSize: '1.7 oz', price: 19.97, originalPrice: 26.99, discount: 26, inStock: true, prescriptionRequired: false, rating: 4.6, reviews: 67890, description: 'Oil-free, non-comedogenic gel moisturizer with hyaluronic acid. Instantly quenches dry skin for smooth, supple, hydrated skin.', ingredients: ['Hyaluronic Acid', 'Dimethicone', 'Glycerin', 'Olive Extract', 'Sodium Hyaluronate'], usage: 'Apply to face and neck after cleansing. Use daily AM and PM.', warnings: 'For external use only. Discontinue if skin irritation develops.' },
  { id: '24', name: 'Hero Cosmetics Mighty Patch Original', brand: 'Hero Cosmetics', category: 'skincare', image: IMG.skin, strength: 'Hydrocolloid', dosageForm: 'Acne Patches', packSize: '36 Patches', price: 12.99, inStock: true, prescriptionRequired: false, rating: 4.5, reviews: 112345, description: 'Award-winning hydrocolloid acne patches. Absorbs pimple gunk overnight without popping. Dermatologist tested.', ingredients: ['Hydrocolloid (Cellulose Gum, Styrene Isoprene Copolymer, Polyisobutylene, Mineral Oil)'], usage: 'Apply to clean, dry skin over blemish. Leave on 6+ hours or overnight. Peel off gently.', warnings: 'For external use only. Do not use on broken or irritated skin.' },
  { id: '25', name: 'The Ordinary Hyaluronic Acid 2% + B5', brand: 'The Ordinary', category: 'skincare', image: IMG.skin2, strength: '2% HA + Vitamin B5', dosageForm: 'Serum', packSize: '30ml', price: 8.90, originalPrice: 12.99, discount: 31, inStock: true, prescriptionRequired: false, rating: 4.5, reviews: 78234, description: 'Multi-depth hydration serum. Three forms of hyaluronic acid for multi-layer hydration. With Vitamin B5 for enhanced skin repair.', ingredients: ['Hyaluronic Acid (Low, Medium, High MW)', 'Vitamin B5 (Panthenol)', 'Pentylene Glycol'], usage: 'Apply a few drops to face AM and PM before moisturizer. Can be mixed with other serums.', warnings: 'Patch test before first use. For external use only.' },

  // ===== BABY CARE (5) =====
  { id: '26', name: 'Aveeno Baby Gentle Wash & Shampoo', brand: 'Aveeno Baby', category: 'baby-care', image: IMG.baby, strength: 'Natural Oat Extract', dosageForm: 'Wash & Shampoo', packSize: '18 fl oz', price: 9.99, originalPrice: 12.99, discount: 23, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 29811, description: '#1 Pediatrician Recommended baby wash brand. Tear-free formula with natural oat extract. Clinically proven gentle for daily use.', ingredients: ['Natural Oat Extract', 'Coconut-derived Cleansers', 'Glycerin', 'Citric Acid'], usage: 'Apply to wet skin and hair. Lather gently and rinse thoroughly.', warnings: 'For external use only. Keep out of reach of children when unattended.' },
  { id: '27', name: 'Aquaphor Baby Healing Ointment', brand: 'Aquaphor', category: 'baby-care', image: IMG.baby, strength: '41% Petrolatum', dosageForm: 'Ointment', packSize: '14 oz', price: 14.89, originalPrice: 18.99, discount: 22, inStock: true, prescriptionRequired: false, rating: 4.9, reviews: 45123, description: '#1 Pediatrician Recommended for diaper rash. Multi-purpose ointment for dry, cracked skin, minor cuts, and diaper rash prevention.', ingredients: ['Petrolatum 41%', 'Mineral Oil', 'Ceresin', 'Lanolin Alcohol', 'Panthenol', 'Bisabolol'], usage: 'Apply as needed to affected areas. Use at every diaper change for rash prevention.', warnings: 'For external use only. Avoid contact with eyes.' },
  { id: '28', name: 'Pampers Sensitive Baby Wipes', brand: 'Pampers', category: 'baby-care', image: IMG.baby, strength: 'Hypoallergenic', dosageForm: 'Wipes', packSize: '672 Count (8 Packs)', price: 19.94, originalPrice: 24.99, discount: 20, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 89234, description: '#1 Pediatrician Recommended brand. Clinically proven for sensitive skin. 0% alcohol, fragrance-free, hypoallergenic.', ingredients: ['Purified Water', 'Citric Acid', 'PEG-40 Hydrogenated Castor Oil', 'Sodium Citrate', 'Sorbitan Caprylate'], usage: 'Gently wipe skin. Dispose after single use. Close lid to retain moisture.', warnings: 'Not flushable. For external use only.' },
  { id: '29', name: 'Desitin Maximum Strength Diaper Rash Cream', brand: 'Desitin', category: 'baby-care', image: IMG.baby, strength: '40% Zinc Oxide', dosageForm: 'Cream', packSize: '4.8 oz', price: 11.49, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 34567, description: '#1 Pediatrician & Dermatologist Recommended diaper rash cream. Maximum strength zinc oxide provides instant relief.', ingredients: ['Zinc Oxide 40%', 'BHT', 'Cod Liver Oil', 'Fragrance', 'Lanolin', 'Methylparaben', 'Petrolatum'], usage: 'Apply at every diaper change, especially at bedtime. Apply thick layer to clean, dry skin.', warnings: 'For external use only. Do not use on broken skin.' },
  { id: '30', name: "Johnson's Baby Bedtime Lotion", brand: "Johnson's Baby", category: 'baby-care', image: IMG.baby, strength: 'NaturalCalm Aromas', dosageForm: 'Lotion', packSize: '13.6 fl oz', price: 7.99, inStock: true, prescriptionRequired: false, rating: 4.7, reviews: 23456, description: 'Clinically proven calming NaturalCalm aromas to help babies relax before bedtime. Hypoallergenic, paraben-free, dye-free.', ingredients: ['Water', 'Glycerin', 'Isopropyl Palmitate', 'Stearic Acid', 'Cetyl Alcohol', 'NaturalCalm Essences'], usage: 'Apply to babys body as part of bedtime routine. Gentle massage helps promote relaxation.', warnings: 'For external use only. Keep out of eyes.' },

  // ===== PERSONAL CARE (5) =====
  { id: '31', name: "Mrs. Meyer's Clean Day Hand Soap", brand: "Mrs. Meyer's", category: 'personal-care', image: IMG.pers, strength: 'Lavender', dosageForm: 'Liquid Hand Soap', packSize: '12.5 fl oz', price: 4.97, inStock: true, prescriptionRequired: false, rating: 4.7, reviews: 67890, description: 'Made with essential oils and plant-derived cleaning ingredients. Paraben-free, phthalate-free, and cruelty-free. Lavender scent.', ingredients: ['Water', 'Sodium Lauryl Sulfate', 'Lauramidopropyl Betaine', 'Glycerin', 'Lavender Oil'], usage: 'Pump soap into wet hands. Lather and rinse thoroughly.', warnings: 'Keep out of reach of children. For external use only.' },
  { id: '32', name: 'Dove Beauty Bar Soap', brand: 'Dove', category: 'personal-care', image: IMG.pers2, strength: '1/4 Moisturizing Cream', dosageForm: 'Bar Soap', packSize: '8 Bars (3.75 oz each)', price: 9.97, originalPrice: 12.99, discount: 23, inStock: true, prescriptionRequired: false, rating: 4.8, reviews: 156789, description: '#1 Dermatologist Recommended bar soap. With 1/4 moisturizing cream for softer, smoother skin. Mild, gentle cleanser.', ingredients: ['Sodium Lauroyl Isethionate', 'Stearic Acid', 'Sodium Tallowate', 'Sodium Palmitate', 'Lauric Acid', 'Sodium Isethionate'], usage: 'Lather in hands or with washcloth. Apply to body. Rinse thoroughly.', warnings: 'For external use only. Avoid contact with eyes.' },
  { id: '33', name: 'Oral-B Pro 1000 Electric Toothbrush', brand: 'Oral-B', category: 'personal-care', image: IMG.pers, strength: 'CrossAction Brush Head', dosageForm: 'Electric Toothbrush', packSize: '1 Handle + 1 Brush Head', price: 49.94, originalPrice: 69.99, discount: 29, inStock: true, prescriptionRequired: false, rating: 4.6, reviews: 78901, description: '#1 Dentist Recommended toothbrush brand worldwide. 3D cleaning action oscillates, rotates, and pulsates to remove plaque.', ingredients: ['Rechargeable Handle', 'CrossAction Brush Head', 'Charger Base'], usage: 'Charge fully before first use. Brush for 2 minutes, 2 times daily. Replace brush head every 3 months.', warnings: 'Do not use if gums bleed excessively. Consult your dentist.' },
  { id: '34', name: 'Native Deodorant - Coconut & Vanilla', brand: 'Native', category: 'personal-care', image: IMG.pers2, strength: 'Aluminum Free', dosageForm: 'Stick Deodorant', packSize: '2.65 oz', price: 12.97, inStock: true, prescriptionRequired: false, rating: 4.5, reviews: 45678, description: 'Aluminum-free, paraben-free, sulfate-free natural deodorant. Made with coconut oil, shea butter, and tapioca starch.', ingredients: ['Caprylic/Capric Triglyceride', 'Tapioca Starch', 'Ozokerite', 'Coconut Oil', 'Shea Butter', 'Baking Soda'], usage: 'Apply 2-3 swipes to clean, dry underarms daily.', warnings: 'Discontinue use if rash or irritation develops.' },
  { id: '35', name: 'Colgate Total Whitening Toothpaste', brand: 'Colgate', category: 'personal-care', image: IMG.pers, strength: 'Whole Mouth Health', dosageForm: 'Toothpaste', packSize: '4 Pack (5.1 oz each)', price: 14.99, originalPrice: 19.96, discount: 25, inStock: true, prescriptionRequired: false, rating: 4.7, reviews: 34567, description: 'Fights germs for 12 hours. Whitens teeth and fights cavities, gingivitis, plaque, tartar, and bad breath. ADA Accepted.', ingredients: ['Sodium Fluoride 0.24%', 'Triclosan 0.30%', 'Hydrated Silica', 'Sorbitol', 'Glycerin'], usage: 'Brush thoroughly at least twice a day or as directed by a dentist.', warnings: 'Keep out of reach of children under 6. If swallowed, contact Poison Control.' },

  // ===== WELLNESS & FITNESS (5) =====
  { id: '36', name: 'Optimum Nutrition Gold Standard Whey', brand: 'Optimum Nutrition', category: 'wellness', image: IMG.well, strength: '24g Protein', dosageForm: 'Powder', packSize: '5 lbs (73 Servings)', price: 62.99, originalPrice: 79.99, discount: 21, inStock: true, prescriptionRequired: false, rating: 4.7, reviews: 123456, description: '#1 Selling whey protein powder worldwide. 24g protein, 5.5g BCAAs, 4g glutamine per serving. Double Rich Chocolate flavor.', ingredients: ['Whey Protein Isolate', 'Whey Protein Concentrate', 'Whey Peptides', 'Cocoa', 'Lecithin', 'Aminogen'], usage: 'Mix 1 scoop with 6-8 oz of cold water, milk, or your favorite beverage. Use between meals and post-workout.', warnings: 'Contains milk and soy. Not suitable for those with dairy allergies.' },
  { id: '37', name: 'Vital Proteins Collagen Peptides', brand: 'Vital Proteins', category: 'wellness', image: IMG.well, strength: '20g Collagen', dosageForm: 'Powder', packSize: '24 oz (28 Servings)', price: 27.99, originalPrice: 39.99, discount: 30, inStock: true, prescriptionRequired: false, rating: 4.6, reviews: 89012, description: '#1 Collagen brand in America. Supports healthy hair, skin, nails, and joints. Dissolves easily in hot and cold liquids.', ingredients: ['Bovine Hide Collagen Peptides', 'Hyaluronic Acid', 'Vitamin C'], usage: 'Add 1-2 scoops to coffee, smoothies, water, or recipes. Stir or blend until dissolved.', warnings: 'Consult your healthcare provider before use if pregnant or nursing.' },
  { id: '38', name: 'OLLY Sleep Gummy - Blackberry Zen', brand: 'OLLY', category: 'wellness', image: IMG.well, strength: '3mg Melatonin', dosageForm: 'Gummies', packSize: '50 Gummies', price: 13.99, originalPrice: 17.99, discount: 22, inStock: true, prescriptionRequired: false, rating: 4.5, reviews: 67890, description: 'Delicious gummies to help boost your natural sleep cycle. With Melatonin, L-Theanine, and Botanicals. Blackberry Zen flavor.', ingredients: ['Melatonin 3mg', 'L-Theanine 100mg', 'Chamomile Extract', 'Passionflower Extract', 'Lemon Balm Extract'], usage: 'Adults take 2 gummies 30 minutes before bedtime. Chew thoroughly.', warnings: 'Do not drive or operate machinery after taking. Not for children.' },
  { id: '39', name: 'Athletic Greens AG1 Travel Packs', brand: 'AG1', category: 'wellness', image: IMG.well, strength: '75 Vitamins & Minerals', dosageForm: 'Powder Packets', packSize: '30 Packets', price: 79.00, inStock: true, prescriptionRequired: false, rating: 4.4, reviews: 34567, description: 'Comprehensive daily nutrition in one scoop. 75 high-quality vitamins, minerals, probiotics, and adaptogens. NSF Certified for Sport.', ingredients: ['Spirulina', 'Chlorella', 'Ashwagandha', 'Rhodiola', 'Probiotics 7.2B CFU', 'CoQ10', 'Vitamin C', 'Zinc'], usage: 'Mix 1 packet with 8 oz cold water. Drink daily on an empty stomach for best results.', warnings: 'Consult your physician before use if pregnant, nursing, or taking medications.' },
  { id: '40', name: 'Garden of Life Organic Protein Powder', brand: 'Garden of Life', category: 'wellness', image: IMG.well, strength: '30g Protein', dosageForm: 'Powder', packSize: '2.4 lbs (28 Servings)', price: 39.99, originalPrice: 54.99, discount: 27, inStock: true, prescriptionRequired: false, rating: 4.5, reviews: 56789, description: 'USDA Organic, Non-GMO plant protein. 30g complete protein from peas, sprouted grains, and seeds. Chocolate flavor.', ingredients: ['Organic Pea Protein', 'Organic Sprouted Brown Rice Protein', 'Organic Chia Seed', 'Organic Flax Seed', 'Organic Cocoa'], usage: 'Mix 1 scoop with 8 oz water, juice, or smoothie. Use 1-2 times daily.', warnings: 'Contains tree nuts (coconut). Not suitable for those with nut allergies.' },
];

// ============ SERVICES, BADGES, ETC (unchanged) ============
export const featuredServices = [
  { icon: 'RefreshCw', title: 'Refill Prescriptions', description: 'Quick and easy prescription refills' },
  { icon: 'Upload', title: 'Upload Prescription', description: 'Securely upload your prescription' },
  { icon: 'MessageCircle', title: 'Pharmacist Consultation', description: '24/7 expert guidance' },
  { icon: 'Calendar', title: 'Subscription Delivery', description: 'Never run out of your medicines' },
];

export const trustBadges = [
  { icon: 'Shield', text: 'Licensed Pharmacy' },
  { icon: 'Headphones', text: 'Pharmacist Support' },
  { icon: 'Lock', text: 'Secure Payment' },
  { icon: 'Truck', text: 'Fast Delivery' },
  { icon: 'BadgeCheck', text: 'Verified Medicines' },
];

export const howItWorks = [
  { step: 1, icon: 'Search', title: 'Search or Upload', description: 'Find your medicine or upload prescription' },
  { step: 2, icon: 'UserCheck', title: 'Pharmacist Review', description: 'Our licensed pharmacist verifies your order' },
  { step: 3, icon: 'CreditCard', title: 'Secure Checkout', description: 'Pay safely with multiple payment options' },
  { step: 4, icon: 'Package', title: 'Fast Delivery', description: 'Receive your medicines at your doorstep' },
];

export const faqs = [
  { question: 'How do I upload a prescription?', answer: 'You can upload your prescription by clicking the "Upload Prescription" button in the header or visiting the Prescription page. We accept images, PDFs, and photos taken with your phone.' },
  { question: 'Is it safe to buy medicines online?', answer: 'Yes, we are a fully licensed pharmacy with verified medicines. All orders are reviewed by licensed pharmacists, and we use secure encryption for your data and payments.' },
  { question: 'What payment methods do you accept?', answer: 'We accept all major credit cards, debit cards, PayPal, and digital wallets. All transactions are secured with industry-standard encryption.' },
  { question: 'How long does delivery take?', answer: 'Standard delivery takes 3-5 business days. Express delivery is available for urgent orders and typically arrives within 1-2 business days.' },
  { question: 'Can I return medicines?', answer: 'Due to health and safety regulations, we cannot accept returns of prescription medicines. However, if there is an error with your order, please contact us immediately.' },
  { question: 'How does the subscription work?', answer: 'Our subscription service automatically refills your medications on a schedule you choose. You save 15% on every auto-refill order, and you can pause or cancel anytime.' },
  { question: 'Do you offer family plans?', answer: 'Yes! Our Family Health Bundle lets you manage medications for up to 5 family members under one account with shared savings and a single delivery.' },
];

export const testimonials = [
  { id: 1, name: 'Sokha Chea', location: 'Phnom Penh, Cambodia', rating: 5, text: 'Batto Pharmacy has been a lifesaver! Fast delivery, great prices, and the pharmacist support is amazing. I trust them completely with my family\'s health.', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop', date: 'March 2026' },
  { id: 2, name: 'Mengly Seng', location: 'Siem Reap, Cambodia', rating: 5, text: 'The prescription upload feature is so convenient. I uploaded my prescription and had my medication delivered the next day. Highly recommend!', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop', date: 'February 2026' },
  { id: 3, name: 'Nita Ros', location: 'Battambang, Cambodia', rating: 5, text: 'Best online pharmacy experience. The website is easy to use, prices are competitive, and customer service is outstanding. Been using for 2 years!', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop', date: 'March 2026' },
  { id: 4, name: 'Darith Kim', location: 'Sihanoukville, Cambodia', rating: 5, text: 'As someone with diabetes, I rely on regular medication. Batto Pharmacy\'s auto-refill feature ensures I never run out. Excellent service!', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop', date: 'January 2026' },
  { id: 5, name: 'Sreyneat Oum', location: 'Kampot, Cambodia', rating: 5, text: 'Love the 24/7 pharmacist consultation. I had questions about my medication and got instant answers. Professional and caring service.', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop', date: 'February 2026' },
  { id: 6, name: 'Rithy Chhea', location: 'Kep, Cambodia', rating: 5, text: 'Switched from my local pharmacy to Batto Pharmacy and couldn\'t be happier. Better prices, faster delivery, and top-notch customer service.', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop', date: 'March 2026' },
];

export const healthTips = [
  { id: 1, title: '5 Ways to Boost Your Immunity This Season', excerpt: 'Discover simple daily habits that can strengthen your immune system and keep you healthy all year round.', category: 'Wellness', readTime: '4 min', image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=400&fit=crop', date: 'June 10, 2025' },
  { id: 2, title: 'Understanding Your Prescription Labels', excerpt: 'Learn how to read and understand the important information on your medication labels for safer use.', category: 'Medication', readTime: '3 min', image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600&h=400&fit=crop', date: 'June 8, 2025' },
  { id: 3, title: 'Managing Diabetes: A Family Guide', excerpt: 'Comprehensive tips for families supporting a loved one with diabetes, from diet to medication management.', category: 'Diabetes', readTime: '6 min', image: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600&h=400&fit=crop', date: 'June 5, 2025' },
];

export const seasonalAlerts = [
  { id: 1, title: 'Summer Skin Protection', message: 'Stock up on SPF and after-sun care. UV levels are at their highest!', icon: 'Sun', color: 'amber' },
  { id: 2, title: 'Allergy Season is Here', message: 'Antihistamines and nasal sprays available with 20% off this month.', icon: 'Wind', color: 'green' },
];

export const journeyMilestones = [
  { year: '2018', title: 'The Beginning', description: 'Founded by Dr. Maya Chen with a vision to make quality healthcare accessible to everyone, everywhere.' },
  { year: '2019', title: 'First 1,000 Customers', description: 'Reached our first milestone and launched our 24/7 pharmacist consultation service.' },
  { year: '2020', title: 'Pandemic Response', description: 'Expanded delivery services and offered free consultations to help communities through COVID-19.' },
  { year: '2022', title: 'National Expansion', description: 'Grew to serve all 50 states with same-day delivery in major metro areas.' },
  { year: '2024', title: '50,000+ Families', description: 'Trusted by over 50,000 families. Launched our subscription and family health bundle programs.' },
  { year: '2025', title: 'AI-Powered Care', description: 'Introduced smart medication reminders and personalized health recommendations.' },
];

export const coreValues = [
  { icon: 'Heart', title: 'Compassion First', description: 'Every interaction is guided by genuine care for your wellbeing. You are not just a customer, you are family.' },
  { icon: 'Shield', title: 'Trust & Safety', description: 'Licensed pharmacists review every order. We only stock verified medicines from trusted manufacturers.' },
  { icon: 'Users', title: 'Community', description: 'We believe in building healthier communities together. Our referral program and family plans reflect this.' },
  { icon: 'Zap', title: 'Innovation', description: 'From AI-powered reminders to seamless prescription uploads, we use technology to simplify your health journey.' },
];

export const impactStats = [
  { number: '50,000+', label: 'Families Served', icon: 'Users' },
  { number: '4.8/5', label: 'Average Rating', icon: 'Star' },
  { number: '500,000+', label: 'Orders Delivered', icon: 'Package' },
  { number: '24/7', label: 'Pharmacist Support', icon: 'Clock' },
];

export const teamMembers = [
  { name: 'Dr. Maya Chen', role: 'Founder & CEO', specialty: 'Clinical Pharmacy', avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&h=300&fit=crop', quote: 'Healthcare should be accessible, affordable, and caring.' },
  { name: 'Dr. James Wilson', role: 'Chief Pharmacist', specialty: 'Medication Therapy', avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&h=300&fit=crop', quote: 'Every prescription tells a story. We listen.' },
  { name: 'Dr. Priya Patel', role: 'Head of Patient Care', specialty: 'Chronic Disease Management', avatar: 'https://images.unsplash.com/photo-1594824476967-48c8b964ac31?w=300&h=300&fit=crop', quote: 'Caring for patients means caring for families.' },
];

export const offers = [
  { id: 1, type: 'first-order', title: 'Welcome to Batto Pharmacy!', subtitle: 'First Order Discount', discount: '20% OFF', code: 'WELCOME20', description: 'Get 20% off your first order. No minimum purchase required.', validUntil: 'July 31, 2025', color: 'from-teal-500 to-emerald-500' },
  { id: 2, type: 'subscription', title: 'Subscribe & Save', subtitle: 'Auto-Refill Program', discount: '15% OFF', code: 'AUTO15', description: 'Save 15% on every auto-refill order. Set your schedule, we handle the rest.', validUntil: 'Ongoing', color: 'from-blue-500 to-indigo-500' },
  { id: 3, type: 'bundle', title: 'Family Health Bundle', subtitle: 'Care for Everyone', discount: '25% OFF', code: 'FAMILY25', description: 'Bundle medications for your whole family and save 25%. Up to 5 members.', validUntil: 'August 15, 2025', color: 'from-rose-500 to-pink-500' },
  { id: 4, type: 'referral', title: 'Refer a Friend', subtitle: 'Share the Care', discount: '$10 + $10', code: 'Unique link', description: 'You get $10, your friend gets $10. Unlimited referrals. Spread the health!', validUntil: 'Ongoing', color: 'from-amber-500 to-orange-500' },
];

export const subscriptionPlans = [
  { id: 'monthly', name: 'Monthly Care', price: 0, savings: '15%', features: ['15% off every refill', 'Free standard delivery', 'Email reminders', 'Cancel anytime'], popular: false },
  { id: 'quarterly', name: 'Quarterly Wellness', price: 0, savings: '20%', features: ['20% off every refill', 'Free express delivery', 'SMS + Email reminders', 'Priority pharmacist access', 'Health tips newsletter'], popular: true },
  { id: 'annual', name: 'Annual Health+', price: 0, savings: '25%', features: ['25% off every refill', 'Free same-day delivery', 'All reminder channels', 'Dedicated pharmacist', 'Family plan (up to 5)', 'Exclusive member offers'], popular: false },
];

export const dealOfTheDay = {
  product: { id: '37', name: 'Vital Proteins Collagen Peptides', brand: 'Vital Proteins', image: IMG.well, price: 27.99, originalPrice: 39.99 },
  discount: 40,
  specialPrice: 23.99,
  endsIn: { hours: 8, minutes: 42, seconds: 15 },
};
